<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="kavbalas" failures="2" tests="2" name="Default test(failed)" time="0.061" errors="0" timestamp="3 Apr 2019 13:16:56 GMT">
  <testcase classname="com.ibm.selenium.maven.CalculatorTest" name="testdiv" time="0.03">
    <failure type="java.lang.AssertionError" message="expected [200] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [0]
	at com.ibm.selenium.maven.CalculatorTest.testdiv(CalculatorTest.java:56)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testdiv -->
  <testcase classname="com.ibm.selenium.maven.CalculatorTest" name="testsub" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [10] but found [-10]">
      <![CDATA[java.lang.AssertionError: expected [10] but found [-10]
	at com.ibm.selenium.maven.CalculatorTest.testsub(CalculatorTest.java:35)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testsub -->
</testsuite> <!-- Default test(failed) -->
